function Hd = dcblock
%dcblock Returns a discrete-time filter object.
% Author: ECE486 Spring 2015 Lab Group 2
% Author: Jacob Allenwood, Travis Russell, Jeremiah Simonsen
%
% This function generates a high-pass filter for the purpose of filtering
% the samples input waveform for the FSK demodulator developed for Lab 4.
%
% The filter is designed for a sample rate of 48 ksps and rejects below 60
% Hz and passes above 300 Hz. The purpose of this filter is to reject DC
% because it is unlikely that the input waveform will be exactly centered
% at 1.5 V. The pass and stop bands were selected somewhat arbitrarily to
% reject DC while keep filter order low.

% MATLAB Code
% Generated by MATLAB(R) 8.2 and the Signal Processing Toolbox 6.20.
% Generated on: 24-Mar-2015 17:16:51

% Elliptic Highpass filter designed using FDESIGN.HIGHPASS.

% All frequency values are in Hz.
Fs = 48000;  % Sampling Frequency

Fstop = 60;      % Stopband Frequency
Fpass = 300;     % Passband Frequency
Astop = 80;      % Stopband Attenuation (dB)
Apass = 0.5;     % Passband Ripple (dB)
match = 'both';  % Band to match exactly

% Construct an FDESIGN object and call its ELLIP method.
h  = fdesign.highpass(Fstop, Fpass, Astop, Apass, Fs);
Hd = design(h, 'ellip', 'MatchExactly', match);

% Get the transfer function values.
[b, a] = tf(Hd);
g = prod(Hd.ScaleValues);				% Calculate gain factor

% Convert to a singleton filter.
Hd = dfilt.df2(b, a);
a = Hd.Denominator; b = Hd.Numerator;	% Grab coefficients
z = roots(b); p = roots(a);				% Calculate poles/zeros
zp2biquad(z,p,g,'dcblock.c');			% Dump filter coefs to file



% [EOF]
