/*!
 * @file
 * 
 * @brief ECE 486 Spring 2015 Lab 4 - Header file declaring externally
 * defined filter coefficients.
 * 
 * @author ECE486 Lab Group 2
 * @author Jacob Allenwood, Travis Russell, Jeremiah Simonsen
 * 
 * @date Mar 26, 2015
 * 
 * This file contains the declarations for the mixer lookup table for use
 * externally. The table is automatically generated by the generate_mixer()
 * function defined in generate_mixer.m
 *
 * This header file must be included by any program that uses the mixer
 * coefficients generated by the generate_mixer() MATLAB function
 * 
 */

#ifndef MIXER_COEF_H
#define MIXER_COEF_H

extern int n_mixer;
extern float mixer_coef[];

#endif