%% ECE486 Lab 4 - Task 3/4
% This script tests the output of the zp2biquad() function written for Task 3. 
% The filter designed in Task 2 was split into 5 biquad sections using the
% coefficients generated by the zp2biquad() function.
%
% Authors: Jacob Allenwood, Travis Russell, Jeremiah Simonsen
% ECE 486 - Laboratory 3
% March 10, 2015

b1 = [1, 0.536782, 1];
b2 = [1, -1.17636, 1];
b3 = [1, -1.99996, 1];
b4 = [1, -1.46681, 1];
b5 = [1, -1.99969, 0.999995];
b6 = [1, -1.99949, 1];

a1 = [1, -1.82119, 0.863015];
a2 = [1, -1.76869, 0.892714];
a3 = [1, -1.9373, 0.944014];
a4 = [1, -1.77323, 0.963391];
a5 = [1, -1.97833, 0.980678];
a6 = [1, -1.99864, 1.00022];

g = 0.000300412;

% x = rand(1,1001);
x = chirp(1:1001,1,1001,48000);

y1 = filter(g.*b1,a1,x);
y2 = filter(b2,a2,y1);
y3 = filter(b3,a3,y2);
y4 = filter(b4,a4,y3);
y5 = filter(b5,a5,y4);
y6 = filter(b6,a6,y5);

Hf_in = fft(x);
Hf_out = fft(y6);
f = linspace(0,1,length(x));
figure(1); hold on;
plot(f,20*log10(abs(Hf_out./Hf_in)));
