%% ECE486 Lab 3 - Task 3/4
% This script tests the output of the zp2biquad() function written for Task 3. 
% The filter designed in Task 2 was split into 5 biquad sections using the
% coefficients generated by the zp2biquad() function.
%
% Authors: Jacob Allenwood, Travis Russell, Jeremiah Simonsen
% ECE 486 - Laboratory 3
% March 10, 2015

b1 = [1, 2, 1];
b2 = [1, -2, 1];
b3 = [1, 0.851559, 1];
b4 = [1, -1.90211, 1];
b5 = [1, 1.17557, 1];

a1 = [1, -0.224858, 0.36];
a2 = [1, -0.790406, 0.3844];
a3 = [1, -1.08994e-16, 0.7921];
a4 = [1, -1.50477, 0.8649];
a5 = [1, 1.15206, 0.9604];

g = 0.0264722;

x = rand(1,1001);

y1 = filter(g.*b1,a1,x);
y2 = filter(b2,a2,y1);
y3 = filter(b3,a3,y2);
y4 = filter(b4,a4,y3);
y5 = filter(b5,a5,y4);

Hf_in = fft(x);
Hf_out = fft(y5);
f = linspace(0,1,length(x));
plot(f,20*log10(abs(Hf_out./Hf_in)));
