%% ECE486 Lab 3 - Task 3/4
% This script is a secondary test of the zp2biquad() function written for Task 3. 
% The filter designed in Task 2 was split into 5 biquad sections using the
% coefficients generated by the zp2biquad() function.
%
% Authors: Jacob Allenwood, Travis Russell, Jeremiah Simonsen
% ECE 486 - Laboratory 3
% March 10, 2015

f = linspace(0,0.5,1001);
z = exp(1i*2*pi*f);
G_1 = (1 + 2*z.^(-1) + 1*z.^(-2))./(1 - 0.224858*z.^(-1) ...
    + 0.36*z.^(-2));
G_2 = (1 - 2*z.^(-1) + 1*z.^(-2))./(1 - 0.790406*z.^(-1) ... 
    + 0.3844*z.^(-2));
G_3 = (1 + 0.851559*z.^(-1) + 1*z.^(-2))./(1 - 1.08994e-16*z.^(-1) ... 
    + 0.7921*z.^(-2));
G_4 = (1 - 1.90211*z.^(-1) + 1*z.^(-2))./(1 - 1.50477*z.^(-1) ... 
    + 0.8649*z.^(-2));
G_5 = (1 + 1.17557*z.^(-1) + 1*z.^(-2))./(1 + 1.15206*z.^(-1) ... 
    + 0.9604*z.^(-2));

plot(f,20*log10(abs(0.0264722*G_1.*G_2.*G_3.*G_4.*G_5)))
axis([0 0.5 -45 5])
grid on
xlabel('Normalize Frequency, cycles/sample')
ylabel('G(f) Filter Gain, dB')
title('Cascaded Biquads Response')